language: java
jdk: oraclejdk8
script:
  - gradle check
  - gradle build
deploy:
  api_key:
    secure: WQCk/V1VI3tlMRGOKcZx07KZW1MnCsQAtyO4nJR2zezPF+LVg51buVIrdm7+2lrEQ3ai7l/PF0jhhZZfKIeCAmY51nGvESOsFZm4Ty/gzT4xOUyUF/SxHtBxd9JP2H1+GYC/9FJChkuc2eG11S/IEeBmhj0dV88Khj4tIM+zQWeh/qkaSpfCjIBwvZMAZppJtl4ZMlskl4edmN8HQrT9YlOuGQwWnvzFQ2EgI7Hr1kbxEODP21r8TjvhATpqWdxWD5VxLG4oATO28vLx0sFama+OmrN5IV8rIwg1c0iqIE/cKNf3sil5AQCgC0vinNA3veZ8DtQ+ccMZXq2w49/NZ61LmR8M1xkrHwGQh92wjg7cfejQaanwo4dDndokRHkWNvzdzA6bFBkNKY0jFv2iZyI6mS++YtWW+jR73Czl0yNE/RQEHNbsTQ1+8c7fhLqfwixETXKA7RDz8v0KAgjWYgt5GJHaItTZPf9Ef/yMNnJ5JIRVoYOQ0gBtrN3hd03NigaGIbtwr/l2CsFOC31jdcqEOdH44Y7tX4ZByenM9tVSZSIvkxkc4zf9yje/sniy2tBoC7JR/jttlJjXeoZYqh7BEE92vppG0r00NrPy+zszcOI3wyx12Pq+8rHIQeM1tEkRcl3Mc03YRun/pdhmIRtUGZQaRbi7Sziew81EL18=
